module.exports = {


   'Booking Lady Gaga by a fan' : function(client){
      client
       .url('https://starsona-dev.qburst.build/ladygaga')
      .useXpath()
      .click('//button[@class="common-btn action-button sc-kpOJdX lfXDAS"]')
      .click('//p[contains(text(),"Celebrate everyday moments with a personalized vid")]')
      .click('//section[@class="dropdown-wrapper sc-dnqmqq dbIXmq"]')
      .click('//li[contains(text(),"Bat Mitzvah")]')
      .assert.visible('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[1]/div[1]/div[1]/input[1]')
      .setValue('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[1]/div[1]/div[1]/input[1]', 'Gordon')
      .setValue('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[2]/div[1]/div[1]/input[1]', 'Rahul')
      .setValue('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[3]/div[1]/div[1]/div[1]/input[1]', 'Father')
      .click('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[1]/input[1]')
      .click('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[4]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[5]/div[5]')
      .assert.visible('//button[@class="common-btn continue-button sc-kpOJdX lfXDAS"]')
      .pause(1000)
      .click('//button[@class="common-btn continue-button sc-kpOJdX lfXDAS"]')
      .pause(1000)
      .click('//button[@class="common-btn continue-button sc-kpOJdX lfXDAS"]')
      .pause(1000)
      .setValue('//input[@name="email"]', 'rahulj+1@qburst.com')
      .setValue('//input[@name="password"]', '1234567@')
      .click('//button[contains(@class,"sc-kpOJdX hZbcbm")]')
      .waitForElementVisible('//button[@id="booking-script"]')
      .click('//button[@id="booking-script"]')
      .waitForElementVisible('//span[contains(@class,"cardNo")]')
      .click('//span[contains(@class,"cardNo")]')
      .click('//button[@id="booking-payment"]')
      .pause(3000)
      .end();
  },
  'Booking Johnny by a fan' : function(client){
      client
       .url('https://starsona-dev.qburst.build/johnnybravo')
      .useXpath()
      .click('//button[@class="common-btn action-button sc-kpOJdX lfXDAS"]')
      .click('//p[contains(text(),"Celebrate everyday moments with a personalized vid")]')
      .click('//section[@class="dropdown-wrapper sc-dnqmqq dbIXmq"]')
      .click('//li[contains(text(),"Bat Mitzvah")]')
      .assert.visible('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[1]/div[1]/div[1]/input[1]')
      .setValue('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[1]/div[1]/div[1]/input[1]', 'Ramsay')
      .setValue('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[2]/div[1]/div[1]/input[1]', 'Rahul')
      .setValue('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[3]/div[1]/div[1]/div[1]/input[1]', 'Father')
      .click('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[1]/input[1]')
      .click('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[4]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[5]/div[5]')
      .assert.visible('//button[@class="common-btn continue-button sc-kpOJdX lfXDAS"]')
      .pause(1000)
      .click('//button[@class="common-btn continue-button sc-kpOJdX lfXDAS"]')
      .pause(1000)
      .click('//button[@class="common-btn continue-button sc-kpOJdX lfXDAS"]')
      .pause(1000)
      .setValue('//input[@name="email"]', 'rahulj+2@qburst.com')
      .setValue('//input[@name="password"]', '1234567@')
      .click('//button[contains(@class,"sc-kpOJdX hZbcbm")]')
      .waitForElementVisible('//button[@id="booking-script"]')
      .click('//button[@id="booking-script"]')
      .waitForElementVisible('//span[contains(@class,"cardNo")]')
      .click('//span[contains(@class,"cardNo")]')
      .click('//button[@id="booking-payment"]')
      .pause(3000)
      .end();
  },
  'Booking LionKing by a fan' : function(client){
      client
       .url('https://starsona-dev.qburst.build/lionking')
      .useXpath()
      .click('//button[@class="common-btn action-button sc-kpOJdX lfXDAS"]')
      .click('//p[contains(text(),"Celebrate everyday moments with a personalized vid")]')
      .click('//section[@class="dropdown-wrapper sc-dnqmqq dbIXmq"]')
      .click('//li[contains(text(),"Bat Mitzvah")]')
      .assert.visible('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[1]/div[1]/div[1]/input[1]')
      .setValue('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[1]/div[1]/div[1]/input[1]', 'Gregory')
      .setValue('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[2]/div[1]/div[1]/input[1]', 'Rahul')
      .setValue('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[3]/div[1]/div[1]/div[1]/input[1]', 'Brother')
      .click('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[1]/input[1]')
      .click('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[4]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[5]/div[5]')
      .assert.visible('//button[@class="common-btn continue-button sc-kpOJdX lfXDAS"]')
      .pause(1000)
      .click('//button[@class="common-btn continue-button sc-kpOJdX lfXDAS"]')
      .pause(1000)
      .click('//button[@class="common-btn continue-button sc-kpOJdX lfXDAS"]')
      .pause(1000)
      .setValue('//input[@name="email"]', 'rahulj+1@qburst.com')
      .setValue('//input[@name="password"]', '1234567@')
      .click('//button[contains(@class,"sc-kpOJdX hZbcbm")]')
      .waitForElementVisible('//button[@id="booking-script"]')
      .click('//button[@id="booking-script"]')
      .waitForElementVisible('//span[contains(@class,"cardNo")]')
      .click('//span[contains(@class,"cardNo")]')
      .click('//button[@id="booking-payment"]')
      .pause(3000)
      .end();
  },
  'Booking Sanjay by a fan' : function(client){
      client
       .url('https://starsona-dev.qburst.build/ranveersingh')
      .useXpath()
      .click('//button[@class="common-btn action-button sc-kpOJdX lfXDAS"]')
      .click('//p[contains(text(),"Celebrate everyday moments with a personalized vid")]')
      .click('//section[@class="dropdown-wrapper sc-dnqmqq dbIXmq"]')
      .click('//li[contains(text(),"Bat Mitzvah")]')
      .assert.visible('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[1]/div[1]/div[1]/input[1]')
      .setValue('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[1]/div[1]/div[1]/input[1]', 'Ganga')
      .setValue('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[2]/div[1]/div[1]/input[1]', 'Yamuna')
      .setValue('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[3]/div[1]/div[1]/div[1]/input[1]', 'Sister')
      .click('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[1]/input[1]')
      .click('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[4]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[5]/div[5]')
      .assert.visible('//button[@class="common-btn continue-button sc-kpOJdX lfXDAS"]')
      .pause(1000)
      .click('//button[@class="common-btn continue-button sc-kpOJdX lfXDAS"]')
      .pause(1000)
      .click('//button[@class="common-btn continue-button sc-kpOJdX lfXDAS"]')
      .pause(1000)
      .setValue('//input[@name="email"]', 'rahulj+2@qburst.com')
      .setValue('//input[@name="password"]', '1234567@')
      .click('//button[contains(@class,"sc-kpOJdX hZbcbm")]')
      .waitForElementVisible('//button[@id="booking-script"]')
      .click('//button[@id="booking-script"]')
      .waitForElementVisible('//span[contains(@class,"cardNo")]')
      .click('//span[contains(@class,"cardNo")]')
      .click('//button[@id="booking-payment"]')
      .pause(3000)
      .end();
  },
'Booking Kanye by a fan' : function(client){
      client
       .url('https://starsona-dev.qburst.build/fsdfsgs')
      .useXpath()
      .click('//button[@class="common-btn action-button sc-kpOJdX lfXDAS"]')
      .click('//p[contains(text(),"Celebrate everyday moments with a personalized vid")]')
      .click('//section[@class="dropdown-wrapper sc-dnqmqq dbIXmq"]')
      .click('//li[contains(text(),"Bat Mitzvah")]')
      .assert.visible('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[1]/div[1]/div[1]/input[1]')
      .setValue('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[1]/div[1]/div[1]/input[1]', 'Kim')
      .setValue('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[2]/div[1]/div[1]/input[1]', 'Chloe')
      .setValue('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[3]/div[1]/div[1]/div[1]/input[1]', 'Sister')
      .click('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[1]/input[1]')
      .click('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[4]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[5]/div[5]')
      .assert.visible('//button[@class="common-btn continue-button sc-kpOJdX lfXDAS"]')
      .pause(1000)
      .click('//button[@class="common-btn continue-button sc-kpOJdX lfXDAS"]')
      .pause(1000)
      .click('//button[@class="common-btn continue-button sc-kpOJdX lfXDAS"]')
      .pause(1000)
      .setValue('//input[@name="email"]', 'rahulj+1@qburst.com')
      .setValue('//input[@name="password"]', '1234567@')
      .click('//button[contains(@class,"sc-kpOJdX hZbcbm")]')
      .waitForElementVisible('//button[@id="booking-script"]')
      .click('//button[@id="booking-script"]')
      .waitForElementVisible('//span[contains(@class,"cardNo")]')
      .click('//span[contains(@class,"cardNo")]')
      .click('//button[@id="booking-payment"]')
      .pause(3000)
      .end();
  },
  'Booking Tievo by a fan' : function(client){
      client
       .url('https://starsona-dev.qburst.build/testingtester')
      .useXpath()
      .click('//button[@class="common-btn action-button sc-kpOJdX lfXDAS"]')
      .click('//p[contains(text(),"Celebrate everyday moments with a personalized vid")]')
      .click('//section[@class="dropdown-wrapper sc-dnqmqq dbIXmq"]')
      .click('//li[contains(text(),"Bat Mitzvah")]')
      .assert.visible('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[1]/div[1]/div[1]/input[1]')
      .setValue('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[1]/div[1]/div[1]/input[1]', 'Ashley Graham')
      .setValue('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[2]/div[1]/div[1]/input[1]', 'Ash')
      .setValue('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[3]/div[1]/div[1]/div[1]/input[1]', 'Brother')
      .click('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[1]/input[1]')
      .click('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[4]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[5]/div[5]')
      .assert.visible('//button[@class="common-btn continue-button sc-kpOJdX lfXDAS"]')
      .pause(1000)
      .click('//button[@class="common-btn continue-button sc-kpOJdX lfXDAS"]')
      .pause(1000)
      .click('//button[@class="common-btn continue-button sc-kpOJdX lfXDAS"]')
      .pause(1000)
      .setValue('//input[@name="email"]', 'rahulj+2@qburst.com')
      .setValue('//input[@name="password"]', '1234567@')
      .click('//button[contains(@class,"sc-kpOJdX hZbcbm")]')
      .waitForElementVisible('//button[@id="booking-script"]')
      .click('//button[@id="booking-script"]')
      .waitForElementVisible('//span[contains(@class,"cardNo")]')
      .click('//span[contains(@class,"cardNo")]')
      .click('//button[@id="booking-payment"]')
      .pause(3000)
      .end();
  },
  
  'Booking Narcos by a fan' : function(client){
      client
       .url('https://starsona-dev.qburst.build/carlosputin')
      .useXpath()
      .click('//button[@class="common-btn action-button sc-kpOJdX lfXDAS"]')
      .click('//p[contains(text(),"Celebrate everyday moments with a personalized vid")]')
      .click('//section[@class="dropdown-wrapper sc-dnqmqq dbIXmq"]')
      .click('//li[contains(text(),"Bat Mitzvah")]')
      .assert.visible('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[1]/div[1]/div[1]/input[1]')
      .setValue('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[1]/div[1]/div[1]/input[1]', 'Calinos')
      .setValue('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[2]/div[1]/div[1]/input[1]', 'Sikax')
      .setValue('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[3]/div[1]/div[1]/div[1]/input[1]', 'Father')
      .click('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[1]/input[1]')
      .click('/html[1]/body[1]/div[3]/div[2]/div[1]/section[1]/section[2]/section[1]/div[1]/section[1]/div[4]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[5]/div[5]')
      .assert.visible('//button[@class="common-btn continue-button sc-kpOJdX lfXDAS"]')
      .pause(1000)
      .click('//button[@class="common-btn continue-button sc-kpOJdX lfXDAS"]')
      .pause(1000)
      .click('//button[@class="common-btn continue-button sc-kpOJdX lfXDAS"]')
      .pause(1000)
      .setValue('//input[@name="email"]', 'rahulj+2@qburst.com')
      .setValue('//input[@name="password"]', '1234567@')
      .click('//button[contains(@class,"sc-kpOJdX hZbcbm")]')
      .waitForElementVisible('//button[@id="booking-script"]')
      .click('//button[@id="booking-script"]')
      .waitForElementVisible('//span[contains(@class,"cardNo")]')
      .click('//span[contains(@class,"cardNo")]')
      .click('//button[@id="booking-payment"]')
      .pause(3000)
      .end();
  },
};