module.exports = {
  'Signup as a star' : function (client) {
    client
      .url('https://starsona-dev.qburst.build')
      .waitForElementVisible('body', 1000)
      .click('xpath','//button[contains(text(),"Sign Up")]')
      .useXpath()
      .click('//div[@class="jss11 jss9"]//div[3]')
      .click('//*[contains(@class,"svg-inline--fa fa-envelope fa-w-16")]')
      .setValue('//input[@name="firstName"]', 'Tester')
      .setValue('//input[@name="lastName"]', 'D')
      .setValue('//input[@name="email"]', 'karthattilrahul+549@yopmail.com')
      .useXpath()
      .click('//span[contains(@class,"checkmark")]')
      .pause(1000)
      .click('//button[contains(@class,"sc-kpOJdX lfXDAS")]')
      .pause(1000)
      .setValue('//input[@id="profile"]', require('path').resolve('/home/rahul/Desktop/im-a-celebrity-main-t.jpg'))
      .waitForElementVisible('//span[contains(text(),"I like it, continue")] ', 2000)
      .click('//button[contains(@class,"common-btn button sc-kpOJdX lfXDAS")]')
      .pause(1000)
      .click('//button[@id="profilePic"]')
      .click('//li[contains(text(),"Movies / TV")]')
      .click('//li[contains(text(),"Actor")]')
      .waitForElementVisible('//div[@class="align-center align-bottom sc-jGxEUC itwZir"]')
       .click('//div[@class="align-center align-bottom sc-jGxEUC itwZir"]//button[@class="common-btn category sc-kpOJdX lfXDAS"][contains(text(),"Continue")]')
      .click('//button[contains(@class,"sc-kpOJdX lfXDAS")]')
      .pause(1000)
      .click('//button[contains(@class,"common-btn button sc-kpOJdX lfXDAS")]')
      .click('//span[contains(@class,"sc-dPPMrM jOOzuR")]')
      .setValue('//input[contains(@placeholder,"What is your referral code?")]', '911')
      .pause(1000)
      .click('//button[contains(@class,"sc-kpOJdX lfXDAS")]')
      .pause(1000)
      .click('//button[contains(@class,"sc-kpOJdX lfXDAS")]')
      .pause(1000)
      .click('//span[contains(@class,"skip")]')
      .pause(3000)
  }

};