module.exports = {
    login_button: '//button[contains(text(),"Log In")]',
    sign_up_button:'//button[contains(text(),"Sign Up")]',
    sign_up_fan:'//div[@class="jss11 jss9"]//div[2]',
    sign_up_star:'//div[@class="jss11 jss9"]//div[3]',
    sign_up_email_icon:'//*[contains(@class,"svg-inline--fa fa-envelope fa-w-16")]',
    sign_up_fan_submit_button:'button[type=submit]',
    sign_up_star_email_continue_button:'//button[contains(@class,"sc-kpOJdX lfXDAS")]',
    i_like_it_continue_button:'//button[@class="common-btn button sc-kpOJdX lfXDAS"]',
    sign_up_star_image_continue_button:'//button[@id="profilePic"]',
    sign_up_star_category_continue_button:'//button[@id="category-id-web"]',
    skip_button: '//span[@class="skip"]',
    skip_welcome_video:'//button[@id="skip-welcome-video"]',
    referral_code_button:'/html[1]/body[1]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[6]/span[1]',
    referral_code_continue: '//button[@id="referralCode"]',
    sign_up_price_continue_button:'//button[@id="setprice"]',
    
    login_continue_button: '//button[contains(@class,"sc-kpOJdX hZbcbm")]',
    add_comment_button: '//*[@class="svg-inline--fa fa-telegram-plane fa-w-14 message-icon comment-icon"]',
    video_close_button: '//span[@class="sc-jTzLTM iiQZkV"]',
    profile_button: '/html[1]/body[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/header[1]/div[1]/div[3]/span[1]/button[1]',
    logout_button:'//span[@class="log-out"]',
    tip_5_button:'//li[@id="tip 5"]',
    card_no_button:'//span[@class="cardNo"]',
    payment_button: '//button[@class="common-btn button sc-kpOJdX lfXDAS"]',
    tip_10_button:'//li[@id="tip 10"]',
    tip_20_button:'//li[@id="tip 20"]',
    book_star_button:'//button[@class="common-btn action-button sc-kpOJdX lfXDAS"]',
    shout_out_button:'//p[contains(text(),"Celebrate everyday moments with a personalized vid")]',
    shout_out_dropdown_button:'//section[@class="dropdown-wrapper sc-dnqmqq dbIXmq"]',
    shout_out_dropdown:'//li[contains(text(),"Bat Mitzvah")]',
    shout_out_continue_button:'//button[@class="common-btn continue-button sc-kpOJdX lfXDAS"]',
    shout_out_continue_final_button:'//button[@id="booking-script"]',
    shout_out_booking_payment_button:'//button[@id="booking-payment"]',
    booking_button:'//a[contains(text(),"Bookings")]',
    view_all_bookings:'//span[@class="info-text"]',
    booking_video_button:'//html[1]/body[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/section[1]',
    booking_video_continue_button:'//*[@id="content-wrapper"]/div[2]/div/div[2]/div/div/div/section/section/section[2]/section/button',
    booking_video_close_button:'//span[@class="closeBtn sc-jTzLTM kUcnxM"]',


};