module.exports = {
  'Signup as a star' : function (client) {
    client
      .url('https://starsona-dev.qburst.build')
      .waitForElementVisible('body', 1000)
      .click('xpath','//button[contains(text(),"Sign Up")]')
      .useXpath()
      .click('//span[@class="sc-bOCYYb cMqdQI"]')
      .click('//*[contains(@class,"svg-inline--fa fa-envelope fa-w-16")]')
      .setValue('//input[@placeholder="First Name"]', 'Tester')
      .setValue('//input[@placeholder="Last Name"]', 'D')
      .setValue('//input[@placeholder="Where do you want your bookings to go?"]', 'karthattilrahul+60@yopmail.com')
      .useXpath()
      .click('//span[contains(@class,"checkmark")]')
      .pause(1000)
      .click('//button[contains(@class,"sc-kpOJdX lfXDAS")]')
      .waitForElementVisible('//div[@class="fans-want sc-FQuPU TWBaB"]', 2000)
      .setValue('//input[@id="profile"]', require('path').resolve('/home/rahul/Desktop/im-a-celebrity-main-t.jpg'))
      .waitForElementVisible('//span[contains(text(),"I like it, continue")] ', 2000)
      .click('//button[contains(@class,"common-btn button sc-kpOJdX lfXDAS")]')
      .pause(1000)
      .click('//button[contains(text(),"Continue")]')
      .click('//li[contains(text(),"Movies / TV")]')
      .click('//li[contains(text(),"Actor")]')
      .pause(1000)
      .click('//div[contains(@class,"align-center align-bottom sc-bbkauy bvevtw")]//button[contains(@class,"sc-kpOJdX lfXDAS")][contains(text(),"Continue")]')
      .pause(1000)
      .click('//button[contains(@class,"common-btn button sc-kpOJdX lfXDAS")]')
      .click('//span[contains(@class,"sc-dPPMrM jOOzuR")]')
      .setValue('//input[contains(@placeholder,"What is your referral code?")]', '911')
      .pause(1000)
      .click('//button[contains(@class,"sc-kpOJdX lfXDAS")]')
      .pause(1000)
      .click('//button[contains(@class,"sc-kpOJdX lfXDAS")]')
      .pause(1000)
      .click('//span[contains(@class,"skip")]')
      .pause(3000)
  }

};